--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: db 
  template:
    metadata:
      name: database 
      labels:
       app: db
    spec: 
     containers:
       - name: postgressdb
         image: library/postgres:13-alpine
         env: 
           - name: POSTGRES_USER
             value: saleor
           - name: POSTGRES_PASSWORD
             value: saleor
         ports: 
           - containerPort: 5432
             protocol: TCP      
--- 
apiVersion: v1
kind: Service
metadata: 
  name: service-db
spec:
  type: LoadBalancer 
  selector:
    app: db 
  ports:
    - port: 35000
      targetPort: 5432
      nodePort: 30000
      protocol: TCP